version: "3.7"
services:
  app:
    build:
      args:
        user: victor
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: forum
    container_name: forum-app
    restart: unless-stopped
    working_dir:  /var/www
    volumes:
      - ./:/var/www
    networks:
      - forum
  db:
    image: mysql:5.7
    container_name: forum-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - forum

  nginx:
    image: nginx:1.17-alpine
    container_name: forum-nginx
    restart: unless-stopped
networks:
  forum:
    driver: bridge
